apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: production-ready
  namespace: rabbitmq-system
spec:
  replicas: 3
  resources:
    requests:
      cpu: 2
      memory: 4Gi
    limits:
      cpu: 2
      memory: 4Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = ignore
      vm_memory_high_watermark_paging_ratio = 0.99
      disk_free_limit.relative = 1.0
  persistence:
    storageClassName: ssd
    storage: "500Gi"
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers: []
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: "topology.kubernetes.io/zone"
              whenUnsatisfiable: DoNotSchedule
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: production-perf-test
  namespace: rabbitmq-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq-perf-test
  template:
    metadata:
      labels:
        app: rabbitmq-perf-test
      annotations:
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
    spec:
      containers:
      - name: perftest
        # https://hub.docker.com/r/pivotalrabbitmq/perf-test/tags
        image: pivotalrabbitmq/perf-test:2.12.0
        resources:
          limits:
            cpu: 2
            memory: 3G
          requests:
            cpu: 1
            memory: 1G
        command:
          - /bin/bash
          - -c
        args:
          - |-
            bin/runjava com.rabbitmq.perf.PerfTest \
              --uri "amqp://$RABBITMQ_USER:$RABBITMQ_PASS@$RABBITMQ_SERVICE:5672/%2f"
        env:
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: production-ready-default-user
              key: username
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: production-ready-default-user
              key: password
        - name: RABBITMQ_SERVICE
          value: production-ready

        - name: PRODUCER_SCHEDULER_THREADS
          value: "10"
        - name: PRODUCERS
          value: "100"
        - name: PRODUCER_RANDOM_START_DELAY
          value: "60"
        - name: VARIABLE_RATE
          value: "10:20,11:20,9:20"
        - name: CONFIRM
          value: "1"
        - name: ROUTING_KEY
          value: "production-non-durable"
        - name: SIZE
          value: "100"

        - name: CONSUMERS_THREAD_POOLS
          value: "10"
        - name: CONSUMERS
          value: "100"

        - name: HEARTBEAT_SENDER_THREADS
          value: "500"
        - name: NIO_THREAD_POOL
          value: "500"

        - name: QUEUE_PATTERN
          value: "production-non-durable-%d"
        - name: QUEUE_PATTERN_FROM
          value: "1"
        - name: QUEUE_PATTERN_TO
          value: "100"
        - name: QUEUE_ARGS
          value: "x-max-length=100"
        - name: AUTO_DELETE
          value: "false"

        - name: METRICS_PROMETHEUS
          value: "true"
