apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: cpu-stealing
  namespace: chaos-testing
spec:
  mode: one
  selector:
    namespaces:
    - default
    labelSelectors:
      "app.kubernetes.io/component": "rabbitmq"
  stressors:
    cpu:
      workers: 2
      load: 80
